// Meridian Health Network — demo content data

export const COLORS = {
  primary: '#1B4F8A',       // Deep healthcare blue
  primaryDark: '#0D3060',
  primaryLight: '#EFF6FF',
  accent: '#0D9488',        // Health teal
  accentLight: '#ECFDF5',
  alert: '#E85D04',
  alertLight: '#FFF7ED',
  neutral: '#111827',
  neutralMid: '#374151',
  muted: '#6B7280',
  background: '#F4F7FB',
  surface: '#FFFFFF',
  border: '#E2E8F0',
  borderDark: '#CBD5E1',
  // Section colors
  sectionNews: '#1B4F8A',
  sectionConditions: '#0D9488',
  sectionPhysician: '#6D28D9',
  sectionCourses: '#B45309',
};

export const PIANO_CONFIG = {
  AID: 'QiNgMM49pu',
  // Resource IDs — set these in Piano Composer and update here
  PHYSICIAN_RESOURCE_ID: 'PHYSICIAN_INSIDER',
  COURSE_RESOURCE_ID: 'COURSE_ACCESS',
  PREMIUM_RESOURCE_ID: 'PREMIUM_MEMBER',
};

// ── CONDITIONS ────────────────────────────────────────────────────────────────

export const CONDITIONS = [
  {
    slug: 'multiple-sclerosis',
    name: 'Multiple Sclerosis',
    shortName: 'MS',
    tag: 'multiple-sclerosis',
    icon: '🧠',
    affectedCount: '2.9M',
    color: '#6D28D9',
    tagline: 'Navigating MS means navigating your whole life — career, relationships, and everything in between.',
    description: 'Multiple sclerosis is a chronic disease affecting the central nervous system. Meridian provides clinical news, physician perspectives, and patient life guidance for everyone in the MS community.',
    featuredCourseSlug: 'ms-workplace-rights',
  },
  {
    slug: 'type-2-diabetes',
    name: 'Type 2 Diabetes',
    shortName: 'T2D',
    tag: 'diabetes',
    icon: '🩸',
    affectedCount: '37.3M',
    color: '#B45309',
    tagline: 'Managing blood sugar is only part of the picture. Living well with diabetes is the real challenge.',
    description: 'Type 2 diabetes is the most common form of diabetes, affecting how your body processes blood sugar. Our expert content covers treatment advances, nutrition, and the psychological side of diabetes management.',
    featuredCourseSlug: 'diabetes-lifestyle-reset',
  },
  {
    slug: 'rheumatoid-arthritis',
    name: 'Rheumatoid Arthritis',
    shortName: 'RA',
    tag: 'rheumatoid-arthritis',
    icon: '🦴',
    affectedCount: '1.5M',
    color: '#0D9488',
    tagline: 'RA affects your joints — but pain and fatigue affect everything you care about.',
    description: 'Rheumatoid arthritis is an autoimmune condition causing joint inflammation, pain, and fatigue. Our RA coverage spans biologics advances, pain management, and living a full life despite chronic inflammation.',
    featuredCourseSlug: null,
  },
  {
    slug: 'heart-disease',
    name: 'Heart Disease',
    shortName: 'Heart',
    tag: 'heart-disease',
    icon: '❤️',
    affectedCount: '128M',
    color: '#DC2626',
    tagline: 'A heart event changes everything. Understanding your risk and recovery is how you take back control.',
    description: 'Heart disease is the leading cause of death in the US. Our cardiology team covers prevention, recovery after cardiac events, medications, and the emotional journey of heart disease.',
    featuredCourseSlug: null,
  },
];

// ── NEWS ARTICLES (metered — 3 free per month via Composer) ────────────────

export const NEWS_ARTICLES = [
  {
    id: 1,
    slug: 'fda-approves-new-oral-ms-therapy',
    condition: 'multiple-sclerosis',
    tags: ['multiple-sclerosis', 'treatment', 'fda'],
    section: 'news',
    category: 'Treatment',
    title: 'FDA Approves First Once-Daily Oral Therapy for High-Activity Relapsing MS',
    byline: 'MHN Medical Staff',
    date: 'May 22, 2026',
    readTime: '4 min',
    locked: false,
    excerpt: 'Regulatory approval marks a shift away from injection-based therapies for patients with highly active relapsing-remitting multiple sclerosis.',
    body: [
      'The FDA has approved a first-of-its-kind once-daily oral therapy for adults with high-activity relapsing multiple sclerosis, potentially eliminating the need for injection or infusion-based disease-modifying treatments for an estimated 400,000 eligible patients.',
      'The approval, granted Friday following a priority review designation, comes after two Phase III trials demonstrated a 47% reduction in annualized relapse rate compared to injectable interferon beta-1a. The drug, which targets S1P receptors to sequester lymphocytes in lymph nodes, showed a manageable safety profile with cardiac monitoring required at treatment initiation.',
      '"This changes the conversation we have in the clinic," said Dr. Sarah Chen, director of the MS Center at Northwestern University Medical Center. "For patients who have been hesitant about injectable therapies — which is a significant portion of newly diagnosed patients — this removes a real barrier to starting effective treatment quickly."',
      'The manufacturer announced that a patient assistance program will cover costs for commercially insured patients with high out-of-pocket exposure. Wholesale acquisition cost is expected to be announced this week.',
      'The approval adds to a growing class of oral MS therapies including existing S1P modulators and fumarate-based treatments, but distinguishes itself in the once-daily dosing schedule and in the specific patient population — those with two or more relapses in the prior year or evidence of active MRI lesions.',
      'Neurologists said the approval is expected to prompt updated prescribing guidelines from the American Academy of Neurology by Q3 2026. Advocacy groups have already signaled plans to pressure insurers to move the drug to formulary Tier 2 status.',
    ],
  },
  {
    id: 2,
    slug: 'exercise-cognitive-decline-ms-study',
    condition: 'multiple-sclerosis',
    tags: ['multiple-sclerosis', 'research', 'exercise', 'cognitive'],
    section: 'news',
    category: 'Research',
    title: 'Aerobic Exercise Slows Cognitive Decline in MS by 34%, Study Finds',
    byline: 'MHN Research Desk',
    date: 'May 18, 2026',
    readTime: '5 min',
    locked: false,
    excerpt: 'A five-year longitudinal study of 1,200 MS patients offers the strongest evidence yet that structured aerobic exercise protects cognitive function as the disease progresses.',
    body: [
      'A five-year longitudinal study published this week in the journal Neurology found that MS patients who maintained a structured aerobic exercise regimen experienced 34% less cognitive decline compared to sedentary controls — evidence researchers say is compelling enough to prompt immediate changes in neurological care protocols.',
      'The study followed 1,200 patients across 12 US medical centers, controlling for disease-modifying therapy use, EDSS score, and baseline cognitive function. Participants in the aerobic group completed at least 150 minutes per week of moderate-intensity activity — walking, cycling, or swimming — monitored via wearables.',
      'The cognitive protection was particularly pronounced in areas of processing speed and memory encoding, two domains most vulnerable to MS-related neurodegeneration. MRI sub-studies in a subset of 340 participants showed measurable preservation of hippocampal gray matter volume.',
      '"We\'ve known anecdotally that active patients tend to do better cognitively over time," said lead author Dr. James Okafor of the University of Washington. "This study gives us the rigor to say: prescribe exercise. It belongs in the treatment plan, not as a footnote."',
      'The findings add to a growing body of evidence that lifestyle factors modulate neurodegeneration independently of pharmacological treatment, potentially opening a new frontier for combination approaches that pair disease-modifying drugs with structured behavioral interventions.',
    ],
  },
  {
    id: 3,
    slug: 'glp1-drugs-cardiovascular-protection',
    condition: 'heart-disease',
    tags: ['heart-disease', 'diabetes', 'glp1', 'treatment'],
    section: 'news',
    category: 'Cardiology',
    title: 'GLP-1 Drugs Deliver Cardiovascular Protection Even in Non-Diabetic Patients',
    byline: 'MHN Cardiology Desk',
    date: 'May 15, 2026',
    readTime: '5 min',
    locked: false,
    excerpt: 'Major cardiovascular outcomes trial finds GLP-1 receptor agonists reduced major cardiac events by 21% in patients with obesity and elevated CV risk — regardless of diabetes status.',
    body: [
      'Results from a landmark cardiovascular outcomes trial presented at the American College of Cardiology annual meeting show that GLP-1 receptor agonists reduced major adverse cardiovascular events by 21% in patients with obesity and elevated cardiovascular risk — even in patients without diabetes.',
      'The SELECT trial enrolled 17,604 adults with pre-existing cardiovascular disease and a body mass index of 27 or higher but without a diabetes diagnosis. The results upend the conventional framing of GLP-1 drugs as primarily metabolic agents.',
      '"This is cardiovascular medicine, full stop," said Dr. Michael Nissen of the Cleveland Clinic. "We need to stop calling this a diabetes drug class."',
      'The findings are expected to accelerate FDA review of expanded cardiovascular indications and may prompt coverage mandates for Medicare and Medicaid populations with documented CV risk.',
    ],
  },
  {
    id: 4,
    slug: 'chronic-illness-mental-health-underdiagnosed',
    condition: null,
    tags: ['mental-health', 'chronic-illness', 'patient-experience'],
    section: 'news',
    category: 'Patient Health',
    title: 'Depression in Chronic Illness Is Still Massively Underdiagnosed — and Undertreated',
    byline: 'MHN Staff',
    date: 'May 10, 2026',
    readTime: '6 min',
    locked: false,
    excerpt: 'A sweeping analysis of 4 million chronic disease patient records finds that fewer than 20% with comorbid depression received appropriate mental health referrals within the first year of diagnosis.',
    body: [
      'A new analysis of 4 million electronic health records across 28 health systems finds a persistently wide gap between the prevalence of depression in chronic disease patients and the rate at which those patients receive mental health treatment.',
      'Among patients diagnosed with MS, rheumatoid arthritis, heart disease, or type 2 diabetes, 38% met clinical criteria for depression within three years of their primary diagnosis — but fewer than 20% received a formal mental health referral in that same window.',
      '"Chronic illness and depression are biologically and psychologically intertwined," said the study\'s senior author, Dr. Rebecca Torres of UCSF. "But our care systems still treat them as separate problems, with separate specialists, separate billing codes, and separate appointments. Patients fall through that gap every day."',
      'The analysis found particular failure points at the handoff between specialist and primary care — a gap that integrated care models, including several ACOs now piloting co-located behavioral health, are attempting to close.',
      'Advocacy groups have responded by calling for new CMS quality metrics that specifically track mental health screening and follow-through rates in chronic disease populations, arguing the current HEDIS framework inadequately captures the psychosocial burden of long-term illness.',
    ],
  },
  {
    id: 5,
    slug: 'ra-biologic-biosimilar-access',
    condition: 'rheumatoid-arthritis',
    tags: ['rheumatoid-arthritis', 'treatment', 'insurance', 'access'],
    section: 'news',
    category: 'Access & Policy',
    title: 'Biosimilar Uptake for RA Reaches 42% as Insurer Step Therapy Battles Continue',
    byline: 'MHN Policy Desk',
    date: 'May 6, 2026',
    readTime: '4 min',
    locked: false,
    excerpt: 'New data shows nearly half of RA patients newly starting biologic therapy are now prescribed biosimilars — but step therapy requirements are delaying initiation for thousands.',
    body: [
      'Biosimilar prescriptions for rheumatoid arthritis have reached 42% of new biologic starts — a milestone that marks significant progress in the six years since the first adalimumab biosimilar entered the US market.',
      'Data from a national claims analysis covering 2025 prescribing shows particular momentum in Medicare Part D plans, where formulary incentives have accelerated biosimilar-first prescribing among rheumatologists.',
      'But patient advocacy groups warn that step therapy requirements — mandating patients fail on older, cheaper medications before accessing biologics — continue to delay appropriate treatment for an estimated 80,000 RA patients annually.',
      '"The step therapy fight is far from over," said the executive director of the RA Foundation. "We\'re winning on biosimilar access while still losing on the front door."',
    ],
  },
];

// ── PHYSICIAN INSIGHTS (premium — always locked behind Physician Insider plan) ─

export const PHYSICIAN_ARTICLES = [
  {
    id: 1,
    slug: 'conversation-i-wish-id-had-ms-patient',
    condition: 'multiple-sclerosis',
    tags: ['multiple-sclerosis', 'patient-experience', 'physician-pov'],
    category: 'Physician Perspective',
    title: 'The Conversation I Wish I\'d Had With My First MS Patient',
    byline: 'Dr. Sarah Chen, MD',
    bylineTitle: 'Director, MS Center, Northwestern University Medical Center',
    date: 'May 24, 2026',
    readTime: '8 min',
    locked: true,
    excerpt: 'We train neurologists to diagnose and treat. We don\'t train them to sit with a 31-year-old woman who just learned her body is attacking itself — and tell her what her life might look like.',
    intro: 'We train neurologists to diagnose and treat. We don\'t train them to sit with a 31-year-old woman who just learned her body is attacking itself — and tell her what her life might look like. After 18 years in MS neurology, here is what I wish I\'d known at the beginning.',
    body: [
      'My first MS patient was 31. She came in with four months of intermittent double vision and a nagging numbness in her left hand. She\'d attributed both to stress. Her MRI told a different story: classic periventricular lesions, two enhancing, textbook relapsing-remitting MS.',
      'I delivered the diagnosis competently. I explained the pathophysiology. I discussed disease-modifying therapy options — there were fewer then — and gave her a pamphlet from the National MS Society. I answered her questions about medication side effects with clinical precision.',
      'What I did not do was tell her what she actually needed to know: that she would almost certainly keep her job if she wanted to; that most people with MS live decades without requiring mobility aids; that her marriage, if she had or wanted one, could remain whole; that sexual function could be preserved and was worth discussing openly; that the worst thing she could do was make permanent decisions based on worst-case scenarios.',
      'The research we now have on quality of life in MS tells us something that should be unsurprising but somehow still is: the patients who do best are not necessarily the ones on the most aggressive therapies. They are the ones who have the fullest information — about their prognosis, their options, and the resources available to help them navigate every dimension of a life with a chronic illness.',
      'That 31-year-old came back to see me six years later. She\'d changed neurologists twice in between. She told me she\'d spent her first three years post-diagnosis in a state of low-grade terror, afraid to plan, afraid to commit, waiting for the disability she\'d been sure was coming.',
      '"Nobody told me I could still have a career," she said. "Nobody told me to plan my life normally."',
      'I have thought about that conversation — and my failure to have it — almost every week since.',
    ],
  },
  {
    id: 2,
    slug: 'sexual-health-chronic-disease-silence',
    condition: 'multiple-sclerosis',
    tags: ['multiple-sclerosis', 'sexual-health', 'patient-experience', 'physician-pov'],
    category: 'Physician Perspective',
    title: 'Sexual Health in Chronic Disease: Why We Keep Avoiding This Conversation',
    byline: 'Dr. Marcus Webb, MD',
    bylineTitle: 'Neuro-Urology, Johns Hopkins Medicine',
    date: 'May 17, 2026',
    readTime: '9 min',
    locked: true,
    excerpt: 'Up to 85% of people with MS experience some form of sexual dysfunction. Fewer than 25% will ever be asked about it by their neurologist. That gap is a failure of medicine, not of patients.',
    intro: 'Up to 85% of people with MS experience some form of sexual dysfunction. Fewer than 25% will ever be asked about it by their neurologist. That gap is a failure of medicine — not of patients.',
    body: [
      'In neuro-urology, I see the patients who fell through the gap. They waited years to be asked. Some were never asked at all.',
      'The reasons neurologists avoid this conversation are well-documented and, frankly, understandable. Clinic time is limited. Many were not trained to address sexual health in the context of neurological disease. There is discomfort — physician discomfort — in raising a topic that feels both personal and peripheral to the primary disease management question.',
      'But sexual function is not peripheral. It is central to quality of life, to relationship health, to mental health, and to the therapeutic alliance between physician and patient. When patients feel that their full selves are not seen in the clinic, they disengage — from appointments, from medications, from care.',
      'The physiology is worth reviewing. MS-related sexual dysfunction arises from three overlapping mechanisms: primary dysfunction caused by demyelinating lesions in the sensory and motor pathways involved in sexual response; secondary dysfunction resulting from fatigue, spasticity, bladder issues, and pain; and tertiary dysfunction — the psychological and relational consequences of living in a body that has become unpredictable.',
      'Each layer requires a different response. Primary dysfunction often responds to targeted pharmacological intervention. Secondary dysfunction can frequently be addressed through better symptom management of the underlying contributors. Tertiary dysfunction — fear of rejection, grief over bodily change, relationship strain — requires the kind of holistic, unhurried conversation that our current clinical infrastructure makes almost impossible to have.',
      'What I have found, after fifteen years in this practice, is that the most powerful thing I can do for most of my patients is ask the question. Just ask. The asking alone signals that this is a legitimate medical concern, that they are not alone in experiencing it, and that help is available.',
    ],
  },
  {
    id: 3,
    slug: 'ms-workplace-disability-neurologists-role',
    condition: 'multiple-sclerosis',
    tags: ['multiple-sclerosis', 'workplace', 'disability', 'physician-pov'],
    category: 'Physician Perspective',
    title: 'Asking the Hard Questions: Workplace Disability and the Neurologist\'s Role',
    byline: 'Dr. Amara Johnson, MD, PhD',
    bylineTitle: 'Neuroimmunology, Mayo Clinic',
    date: 'May 10, 2026',
    readTime: '7 min',
    locked: true,
    excerpt: 'Neurologists hold enormous influence over whether MS patients stay in the workforce. Most of us were never taught to use it well.',
    intro: 'Neurologists hold enormous influence over whether MS patients stay in the workforce. Most of us were never taught to use it well.',
    body: [
      'Employment is one of the strongest predictors of quality of life in MS — stronger, by some measures, than disability status as measured by EDSS. Patients who remain employed report better mental health, more robust social networks, stronger sense of identity, and better medication adherence.',
      'And yet the rate at which MS patients leave the workforce is striking. Estimates suggest that 50-60% of MS patients will stop working within 10 years of diagnosis. Many leave earlier than medically necessary — pushed by employer inflexibility, inadequate symptom accommodation, and a lack of information about their rights.',
      'Where does the neurologist fit in this picture? Centrally, in ways we rarely acknowledge.',
      'We write the letters that determine accommodations. We document the functional limitations that employers and HR departments act on. We communicate — or fail to communicate — what patients can realistically expect from their disease trajectory, information that directly affects the employment decisions patients make.',
      'I have seen, repeatedly, patients who left jobs they valued based on what they understood to be a neurologist\'s prognosis — a prognosis that was either more pessimistic than warranted or conveyed without the context that might have led them to fight for accommodations instead of an exit.',
      'The ADA reasonable accommodation framework is more powerful than most MS patients realize. Flexible hours to manage fatigue. Remote work during relapse. Modified schedules for infusion appointments. These are legally defensible requests in most workplaces, and a well-written neurologist letter makes the difference between an accommodation granted and a request ignored.',
      'This is not outside our scope. This is medicine — the part that happens between appointments, in the offices and job sites where our patients spend most of their lives.',
    ],
  },
  {
    id: 4,
    slug: 'diet-ms-evidence-vs-hype',
    condition: 'multiple-sclerosis',
    tags: ['multiple-sclerosis', 'nutrition', 'research', 'physician-pov'],
    category: 'Clinical Evidence',
    title: 'Diet and MS: What the Evidence Actually Says (and What It Doesn\'t)',
    byline: 'Dr. David Kim, MD, PhD',
    bylineTitle: 'Neuroimmunology & Integrative Medicine, UCSF',
    date: 'May 3, 2026',
    readTime: '10 min',
    locked: true,
    excerpt: 'Patients arrive in clinic convinced that the right diet will halt their disease. Some are right in ways they don\'t expect. Most are operating on incomplete information that the internet is not equipped to correct.',
    intro: 'Patients arrive in clinic convinced that the right diet will halt their disease. Some are right in ways they don\'t expect. Most are operating on incomplete information.',
    body: [
      'The diet-MS landscape is a minefield of hope, commercial incentive, and genuinely interesting but incomplete science. As a neuroimmunologist who has spent a decade at the intersection of nutrition research and MS clinical care, I want to give you the honest version.',
      'First, what we know with reasonable confidence. The gut microbiome influences immune function in ways that are plausibly relevant to autoimmune disease. Patients with MS have demonstrable differences in gut microbiome composition compared to healthy controls. High-fiber diets consistently produce microbiome profiles associated with anti-inflammatory immune phenotypes. Obesity and metabolic syndrome are associated with worse MS outcomes and accelerated disability progression.',
      'Second, what is promising but not proven. Several dietary protocols — the Swank diet, the OMS diet, a Mediterranean variant — have shown signals in observational studies and small trials. None has been tested in a definitive randomized controlled trial with disability progression as a primary endpoint.',
      'Third, what is almost certainly wrong. The idea that any single dietary intervention can substitute for disease-modifying therapy in high-activity MS is not supported by evidence and potentially dangerous. I have seen patients delay or discontinue effective treatment based on dietary conviction, with consequences that were sometimes irreversible.',
      'The honest synthesis: there is good reason to counsel patients toward a predominantly plant-based, low-processed-food diet with healthy weight maintenance. The evidence for specific MS dietary protocols is weaker than advocates present it, but the general direction of that evidence — toward anti-inflammatory eating patterns — is coherent with what we know about MS immunopathology.',
    ],
  },
];

// ── COURSES (eLearning — always locked behind Course Access or Premium plan) ─

export const COURSES = [
  {
    id: 1,
    slug: 'ms-workplace-rights',
    condition: 'multiple-sclerosis',
    tags: ['multiple-sclerosis', 'workplace', 'course'],
    title: 'Navigating MS at Work: Know Your Rights and Options',
    subtitle: 'A practical guide to ADA accommodations, disclosure decisions, and keeping your career on track.',
    instructor: 'Dr. Amara Johnson, MD, PhD & Employment Law Specialist J. Rivera, Esq.',
    duration: '4 modules · ~2 hours',
    level: 'All levels',
    enrolled: 3842,
    rating: 4.9,
    locked: true,
    featured: true,
    coverColor: '#6D28D9',
    description: 'This course addresses one of the most frequently asked — and least-answered — questions in MS care: what happens to my career? Built for patients within the first five years of diagnosis, it covers the full arc of the employment question: whether and how to disclose, how to request ADA accommodations effectively, how to evaluate remote work and reduced hours options, and how to plan financially for the range of possible futures.',
    modules: [
      { title: 'Understanding Your Rights Under the ADA', duration: '28 min', free: true },
      { title: 'The Disclosure Decision: When, How, and to Whom', duration: '34 min', free: false },
      { title: 'Requesting and Documenting Accommodations', duration: '31 min', free: false },
      { title: 'Career Planning for the Long Term', duration: '27 min', free: false },
    ],
    outcomes: [
      'Understand what counts as a reasonable accommodation under ADA',
      'Know when disclosure helps versus hurts your position',
      'Leave with a written accommodation request letter template',
      'Have a framework for long-range career and financial planning',
    ],
  },
  {
    id: 2,
    slug: 'ms-intimacy-relationships',
    condition: 'multiple-sclerosis',
    tags: ['multiple-sclerosis', 'relationships', 'sexual-health', 'course'],
    title: 'Relationships, Intimacy & MS: A Candid Guide',
    subtitle: 'The conversations about relationships, sexuality, and partnership that the clinic rarely makes time for.',
    instructor: 'Dr. Marcus Webb, MD · Dr. Lisa Park, PsyD (Couples Therapy)',
    duration: '5 modules · ~2.5 hours',
    level: 'All levels',
    enrolled: 5107,
    rating: 4.8,
    locked: true,
    featured: true,
    coverColor: '#DB2777',
    description: 'MS affects intimacy in ways that are common, treatable, and almost never discussed in a neurology appointment. This course — built with both a neuro-urologist and a clinical psychologist specializing in chronic illness — covers sexual function changes, communication with partners, navigating the emotional complexity of bodily change, and evidence-based strategies for maintaining intimate connection across the disease course.',
    modules: [
      { title: 'The Physiology: What MS Does and Why', duration: '24 min', free: true },
      { title: 'Talking to Your Partner: A Framework', duration: '32 min', free: false },
      { title: 'Sexual Function: What Can Change and What Helps', duration: '36 min', free: false },
      { title: 'When Fatigue and Pain Are in the Room', duration: '28 min', free: false },
      { title: 'Dating and New Relationships After Diagnosis', duration: '30 min', free: false },
    ],
    outcomes: [
      'Understand the three layers of MS-related sexual dysfunction',
      'Have language to initiate difficult conversations with partners',
      'Know which symptoms are treatable and what treatments exist',
      'Have strategies for intimacy on high-fatigue days',
    ],
  },
  {
    id: 3,
    slug: 'ms-fatigue-management',
    condition: 'multiple-sclerosis',
    tags: ['multiple-sclerosis', 'fatigue', 'lifestyle', 'course'],
    title: 'MS Fatigue: Science-Based Strategies for Daily Life',
    subtitle: 'Not just "rest more." A full toolkit for managing MS-related fatigue without surrendering your life.',
    instructor: 'Dr. Jennifer Park, MD · OT Specialist M. Torres',
    duration: '4 modules · ~1.75 hours',
    level: 'All levels',
    enrolled: 6221,
    rating: 4.7,
    locked: true,
    featured: false,
    coverColor: '#0D9488',
    description: 'MS fatigue is different from normal tiredness — it\'s a primary neurological symptom with distinct mechanisms and distinct solutions. This course separates fatigue from depression, explains energy conservation principles, covers pharmacological and non-pharmacological management strategies, and provides practical workplace and home modification tools.',
    modules: [
      { title: 'Understanding MS Fatigue vs. Other Fatigue', duration: '22 min', free: true },
      { title: 'Energy Conservation Principles', duration: '28 min', free: false },
      { title: 'Sleep, Exercise, and Pharmacological Options', duration: '30 min', free: false },
      { title: 'Workplace and Home Adaptations', duration: '25 min', free: false },
    ],
    outcomes: [
      'Distinguish MS fatigue from depression and medication side effects',
      'Apply energy banking principles to your daily schedule',
      'Understand which medications help MS fatigue and when to discuss them',
      'Implement home and workplace modifications that reduce energy cost',
    ],
  },
  {
    id: 4,
    slug: 'financial-planning-chronic-illness',
    condition: null,
    tags: ['chronic-illness', 'financial-planning', 'disability', 'course'],
    title: 'Financial Planning After a Chronic Diagnosis',
    subtitle: 'Insurance, disability coverage, and long-range financial planning in the context of ongoing health needs.',
    instructor: 'J. Kim, CFP · D. Wallace, Disability Benefits Specialist',
    duration: '5 modules · ~2.25 hours',
    level: 'All levels',
    enrolled: 2891,
    rating: 4.8,
    locked: true,
    featured: false,
    coverColor: '#1B4F8A',
    description: 'A chronic diagnosis brings financial questions that most people have no framework to answer. This course — built with a certified financial planner and a disability benefits specialist — covers insurance strategy, the SSDI/SSI system, short- and long-term disability coverage, protecting assets against medical costs, and retirement planning when a future health trajectory is uncertain.',
    modules: [
      { title: 'Understanding Your Insurance Options', duration: '30 min', free: true },
      { title: 'Disability Benefits: SSDI, SSI, and Private Plans', duration: '34 min', free: false },
      { title: 'Protecting Assets in a High-Cost Illness', duration: '28 min', free: false },
      { title: 'Long-Range Planning with Uncertainty', duration: '27 min', free: false },
      { title: 'Resources, Assistance Programs, and Advocacy', duration: '26 min', free: false },
    ],
    outcomes: [
      'Know when and how to shift insurance coverage to protect yourself',
      'Understand SSDI qualification requirements and how to apply',
      'Have a framework for financial planning that accounts for a range of disease outcomes',
      'Know which patient assistance and cost-sharing programs you may qualify for',
    ],
  },
  {
    id: 5,
    slug: 'diabetes-lifestyle-reset',
    condition: 'type-2-diabetes',
    tags: ['diabetes', 'lifestyle', 'nutrition', 'course'],
    title: 'The T2D Lifestyle Reset: Evidence-Based Nutrition and Activity',
    subtitle: 'Cutting through the noise on diabetes nutrition, exercise, and remission — what actually works.',
    instructor: 'Dr. Priya Nair, MD, CDE · Registered Dietitian S. Cohen',
    duration: '4 modules · ~2 hours',
    level: 'All levels',
    enrolled: 8144,
    rating: 4.6,
    locked: true,
    featured: false,
    coverColor: '#B45309',
    description: 'The internet is full of type 2 diabetes diet advice, much of it contradictory and some of it dangerous. This course cuts through the noise with evidence-based guidance on carbohydrate management, meal timing, the role of exercise in insulin sensitivity, and what the remission research actually says.',
    modules: [
      { title: 'Carbohydrate Quality vs. Quantity: What Matters', duration: '28 min', free: true },
      { title: 'Exercise and Insulin Sensitivity', duration: '30 min', free: false },
      { title: 'Meal Timing, Intermittent Fasting, and CGM Use', duration: '32 min', free: false },
      { title: 'The Remission Question: What\'s Possible and for Whom', duration: '30 min', free: false },
    ],
    outcomes: [
      'Understand glycemic index vs. glycemic load and why it matters',
      'Know how and when to use exercise for acute glucose management',
      'Have a framework for evaluating whether intermittent fasting is appropriate',
      'Understand the evidence for T2D remission and what it requires',
    ],
  },
];

// ── NEWSLETTER TIERS ──────────────────────────────────────────────────────────

export const NEWSLETTER_TIERS = [
  {
    id: 'free',
    name: 'Health Headlines',
    price: 'Free',
    frequency: 'Weekly',
    description: 'Our weekly digest of the most important health and medical news — curated by the Meridian editorial team.',
    features: [
      'Weekly digest of top health stories',
      'Access to all free site content',
      'Condition-specific news alerts',
      'Breaking clinical trial results',
    ],
    cta: 'Subscribe Free',
    ctaAction: 'esp_subscribe',
    highlighted: false,
  },
  {
    id: 'physician-insider',
    name: 'Physician Insider',
    price: '$9.99/mo',
    priceAnnual: '$89/yr',
    frequency: 'Bi-weekly',
    description: 'Physician-authored perspective pieces, clinical deep-dives, and exclusive expert Q&A delivered to your inbox twice a week.',
    features: [
      'Everything in Health Headlines',
      'Bi-weekly physician POV essays',
      'Clinical research summaries',
      'Monthly Ask-a-Specialist Q&A',
      'Unlimited site access',
      'Early access to new courses',
    ],
    cta: 'Start Physician Insider',
    ctaAction: 'composer_checkout',
    highlighted: true,
    badge: 'Most Popular',
  },
];

// ── MEMBERSHIP PLANS ──────────────────────────────────────────────────────────

export const MEMBERSHIP_PLANS = [
  {
    id: 'free',
    name: 'Reader',
    price: 'Free',
    description: 'Access to general health news and condition overviews, with a 3-article monthly meter on premium content.',
    features: [
      '3 free articles per month',
      'Condition overviews',
      'Health Headlines newsletter',
      'Breaking news alerts',
    ],
    cta: 'Create Free Account',
    highlighted: false,
  },
  {
    id: 'standard',
    name: 'Member',
    price: '$6.99/mo',
    priceAnnual: '$59/yr',
    description: 'Unlimited access to all health news and condition content, plus the Health Headlines newsletter.',
    features: [
      'Unlimited news & condition articles',
      'Health Headlines newsletter',
      'Condition tracking tools',
      'Community forum access',
    ],
    cta: 'Start Membership',
    highlighted: false,
  },
  {
    id: 'premium',
    name: 'Physician Insider',
    price: '$9.99/mo',
    priceAnnual: '$89/yr',
    description: 'Everything in Member, plus full access to Physician Insights content, all courses, and the Physician Insider bi-weekly newsletter.',
    features: [
      'Everything in Member',
      'All Physician Insights articles',
      'Full course library access',
      'Physician Insider newsletter',
      'Monthly Ask-a-Specialist Q&A',
      'Early access to new content',
    ],
    cta: 'Start Physician Insider',
    highlighted: true,
    badge: 'Best Value',
  },
];
